spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    publisher-returns: true   #当消息投递到队列时失败，会返回
    publisher-confirm-type: correlated

