spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        prefetch: 1   #一次取一条消息
        acknowledge-mode: auto #none,关闭ack；manual，手动ack；auto，自动ack(默认)
        retry:
          enabled: true         #开启消费者失败重试
          initial-interval: 1000  # 初始的失败等待为1秒
          multiplier: 3  #下次失败的等待时长，下次等待时长 = multiplier * last-interval
          max-attempts: 4 #最大重试次数
          stateless: true #true无状态；false有状态。如果业务中包含事务，这里改为false

